version: '2'
services:
  MySQLMasterLoadBalancer:
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: tcp
        service: MySQLMaster
        source_port: 3306
        target_port: 3306
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
  MySQLMasterSidekick:
    scale: 1
    start_on_create: true
  MySQLSlaveLoadBalancer:
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - priority: 1
        protocol: tcp
        service: MySQLSLave
        source_port: 3307
        target_port: 3306
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      reinitializing_timeout: 60000
  MySQLSLave:
    scale: 1
    start_on_create: true
  MySQLSlaveSidekick:
    scale: 1
    start_on_create: true
  MySQLMaster:
    scale: 1
    start_on_create: true
